#!/bin/sh -eu

OPAM_BINDIR="$(opam config var bin)"
OPAM_SWITCH="$(opam config var switch)"
OPAM_SHAREDIR="$(opam config var share)/jupyter"

mkdir -p "$OPAM_SHAREDIR/"

cat <<EOF >"$OPAM_SHAREDIR/kernel.json"
{
  "display_name": "OCaml $OPAM_SWITCH",
  "language": "OCaml",
  "argv": [
    "/bin/sh",
    "-c",
    "eval \$(opam config env --switch=$OPAM_SWITCH) && $OPAM_BINDIR/ocaml-jupyter-kernel \"\$@\"",
    "ocaml-jupyter-kernel",
    "-init", "$HOME/.ocamlinit",
    "--merlin", "$OPAM_BINDIR/ocamlmerlin",
    "--verbosity", "app",
    "--connection-file", "{connection_file}"
  ]
}
EOF

echo "Generated kernelspec at $OPAM_SHAREDIR/kernel.json"
